### Testar a raiz do projeto
GET http://localhost:5122

### Listar carros
GET http://localhost:5122/api/carros/listar

### Buscar um carro pelo id
GET http://localhost:5122/api/carros/buscar/1

### Deletar um carro pelo id
DELETE  http://localhost:5122/api/carros/deletar/1

### Cadastrar Cliente
POST http://localhost:5122/api/clientes/cadastrar
Content-Type: application/json

{
    "nome": "Gabriel",
    "telefone": "+12341243456",
    "email": "teste@gmail.com"
}

### Cadastrar carro
POST http://localhost:5122/api/carros/cadastrar
Content-Type: application/json


{
    "placa": "ATR2655",
    "marca": "Suzuki",
    "modelo": "Gran Vitara",
    "cor": "Preto",
    "vagaId": 1,
    "clienteId": 5
}

### Alterar carro
PUT http://localhost:5122/api/carros/alterar/2
Content-Type: application/json

{
    "placa": "ABC123",
    "marca": "Chevrolet",
    "modelo": "Montana",
    "cor": "Branco"
}

### Cadastrar vaga
POST http://localhost:5122/api/vagas/cadastrar
Content-Type: application/json

{
    "numero": "A1"
}

### Listar vagas
GET http://localhost:5122/api/vagas/listar

### Listar Clientes

GET http://localhost:5122/api/clientes/listar

### Cadastrar um recibo
POST http://localhost:5122/api/recibo/cadastrar/1
Content-Type: application/json

### Listar todos os recibos
GET http://localhost:5122/api/recibos/listar