### Testar a raiz do projeto
GET http://localhost:5122

### Cadastrar vaga
POST http://localhost:5122/api/vagas/cadastrar
Content-Type: application/json

{
    "nome": "igor hey matos",
    "telefone": "+12341243456",
    "email": "teste@gmail.com",
    "CarroId": 11
    "numero": "A3"
}

### Cadastrar carro
POST http://localhost:5122/api/carros/cadastrar
Content-Type: application/json


{
    "placa": "ATR2655",
    "marca": "Suzuki",
    "modelo": "Gran Vitara",
    "cor": "Branco",
    "vagaId": 37
}

### Cadastrar Cliente
POST http://localhost:5122/api/clientes/cadastrar
Content-Type: application/json

{
    "nome": "João",
    "telefone": "+12341243456",
    "email": "joao@gmail.com",
    "CarroId": 1
}

### Gerar um recibo
POST http://localhost:5122/api/recibos/cadastrar
Content-Type: application/json

{
  "clienteId": 2,
  "carroId": 2
}

### Listar vagas
GET http://localhost:5122/api/vagas/listar

### Listar carros
GET http://localhost:5122/api/carros/listar

### Listar clientes
GET http://localhost:5122/api/clientes/listar

### Listar recibos
GET http://localhost:5122/api/recibos/listar

### Buscar um carro pelo id
GET http://localhost:5122/api/carros/buscar/1


### Alterar carro
PUT http://localhost:5122/api/carros/alterar/2
Content-Type: application/json

{
    "placa": "ABC123",
    "marca": "Chevrolet",
    "modelo": "Montana",
    "cor": "Branco"
}

### Cadastrar vaga
POST http://localhost:5122/api/vagas/cadastrar
Content-Type: application/json

{
    "numero": "B20"
}

### Listar vagas
GET http://localhost:5122/api/vagas/listar


### Cadastrar um recibo
POST http://localhost:5122/api/recibos/cadastrar
Content-Type: application/json

{
  "clienteId": 6,
  "carroId": 11
}

### Listar todos os recibos
GET http://localhost:5122/api/recibos/listar

### Deletar um carro pelo id
DELETE  http://localhost:5122/api/carros/deletar/6
